---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  product_name: chef
  chef_license: accept-no-persist

platforms:
  - name: ubuntu-18.04
  - name: centos-7.6

suites:
  - name: chef
    provisioner:
      name: chef_zero
    driver:
      dns:
        - 8.8.8.8
        - 199.85.126.10
